# urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path("quick_pair/", views.quick_pair, name='quick_pair'),
    path("create_new_game/", views.create_new_game, name='create_new_game'),
    path("create_new_game/<uuid:optional_uuid>/", views.create_new_game, name='create_new_game_with_uuid'),
    path('check_game_availability/', views.check_game_availability, name='available'),
    path('get_private_id/', views.create_signed_key, name='private_id'),
    path('get_lobby_games/', views.get_lobby_games, name='get_lobby_games'),
    path("config/<uuid:game_uuid>/", views.get_config, name='get_game_config'),
    path('play/<uuid:game_uuid>/', views.play, name='join_new_game'),
    path('update_connected/', views.update_connected, name='update_connected'),
    path("game-state/<uuid:game_uuid>/", views.get_or_update_state, name='get_or_update_state'),
    path('save_game/', views.save_game, name='save_game'),
    path("lessons/", views.lessons, name="lessons"),
    path("lessons/<str:lesson>/", views.lesson, name="lesson"),
    path("variants/", views.variants, name="variants"),
    path("news/", views.news, name="news"),
    path("live/", views.live, name='live'),
    path("board_editor/", views.board_editor, name='board_editor'),
    path("game_search/", views.game_search, name="game_search"),
    path("leaderboards/", views.leaderboards, name="leaderboards"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("inbox/", views.inbox, name="inbox"),
    path("message/<uuid:message_id>/", views.message, name="message"),
    path("usersearch/", views.user_search, name="user_search"),
    path("challenge/<uuid:challenge_id>", views.challenge, name="challenge"),
    path("save_challenge/", views.upsert_challenge, name="upsert_challenge"),
    path("block/", views.block, name="block"),
    path("existing_blocks/", views.existing_blocks, name="existing_blocks"),
    path("is_blocked/", views.is_blocked, name="is_block"),
    path("notifications/", views.notifications, name="notifications"),
    path("update_notifications/", views.update_notifications, name="update_notifications"),
    path("terms-of-service/", views.terms_of_service, name="terms"),
    path("privacy/", views.privacy_policy, name="privacy"),
    path("account/themes", views.change_themes, name="change_themes"),
    path("account/email", views.change_email, name="change_email"),
    path("account/confirm/<str:uidtoken>/<str:token>/", views.confirm_email, name='activate_account'),
    path("account/passwd", views.change_password, name="change_password"),
    path("account/profile", views.edit_profile, name="edit_profile"),
    path("account/close_account", views.close_account, name="close_account"),
]