# Generated by Django 4.2.5 on 2023-09-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
