# Generated by Django 4.2.5 on 2023-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_uuid', models.UUIDField(unique=True)),
                ('white_uuid', models.UUIDField()),
                ('black_uuid', models.UUIDField()),
                ('initiator_uuid', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('lobby_url', models.URLField(unique=True)),
                ('initiator_connected', models.BooleanField(default=False)),
            ],
        ),
    ]
