# Generated by Django 4.2.5 on 2023-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chesslobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesslobby',
            name='lobby_url',
        ),
        migrations.AddField(
            model_name='chesslobby',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chesslobby',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
