# Generated by Django 4.2.5 on 2023-10-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_chesslobby_lobby_url_chesslobby_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslobby',
            name='black_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='chesslobby',
            name='white_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
