# Generated by Django 4.2.6 on 2023-11-05 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_chesslobby_expire_alter_chesslobby_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistoryTable',
            fields=[
                ('gameid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whiteid', models.UUIDField()),
                ('blackid', models.UUIDField()),
                ('moves', models.TextField(default='')),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(auto_now_add=True)),
                ('gametype', models.CharField(default='', max_length=300)),
                ('outcome', models.CharField(default='', max_length=7)),
            ],
        ),
    ]
