# Generated by Django 4.2.6 on 2023-11-06 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gamehistorytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGames',
            fields=[
                ('gameid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whiteid', models.UUIDField()),
                ('blackid', models.UUIDField()),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('gametype', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
