# Generated by Django 4.2.6 on 2023-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_activegames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistorytable',
            old_name='moves',
            new_name='algebraic_moves',
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='FEN_outcome',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='computed_moves',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gamehistorytable',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
