# Generated by Django 4.2.6 on 2023-11-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_moves_gamehistorytable_algebraic_moves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistorytable',
            name='end_reason',
            field=models.CharField(default='', max_length=85),
        ),
    ]
