# Generated by Django 4.2.6 on 2023-11-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_gamehistorytable_end_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistorytable',
            old_name='end_reason',
            new_name='termination_reason',
        ),
    ]
