# Generated by Django 4.2.6 on 2023-11-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_end_reason_gamehistorytable_termination_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistorytable',
            name='termination_reason',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
    ]
