# Generated by Django 4.2.7 on 2023-11-09 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_gamehistorytable_termination_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChatMessages',
            fields=[
                ('messageid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gameid', models.UUIDField()),
                ('sender_color', models.CharField(max_length=5, null=True)),
                ('sender', models.UUIDField()),
                ('sender_username', models.CharField(default='Anonymous', max_length=150)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('messageid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gameid', models.UUIDField()),
                ('sender_color', models.CharField(max_length=5, null=True)),
                ('sender', models.UUIDField()),
                ('sender_username', models.CharField(default='Anonymous', max_length=150)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
