# Generated by Django 4.2.7 on 2023-11-09 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_activechatmessages_chatmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activechatmessages',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
