# Generated by Django 4.2.7 on 2023-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_activechatmessages_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
