# Generated by Django 4.2.7 on 2023-11-14 22:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_chatmessages_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChatMessages',
            fields=[
                ('active_message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.UUIDField()),
                ('sender_color', models.CharField(max_length=5, null=True)),
                ('sender', models.UUIDField()),
                ('sender_username', models.CharField(default='Anonymous', max_length=150)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveGames',
            fields=[
                ('active_game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('white_id', models.UUIDField()),
                ('black_id', models.UUIDField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('gametype', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('author', models.CharField(default='', max_length=150)),
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessLobby',
            fields=[
                ('lobby_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('white_id', models.UUIDField(null=True)),
                ('black_id', models.UUIDField(null=True)),
                ('initiator_name', models.CharField(default='Anonymous', max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('expire', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('initiator_connected', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
