# Generated by Django 4.2.7 on 2023-11-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_activechatmessages_activegames_blogposts_chesslobby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPosts',
        ),
    ]
