# Generated by Django 4.2.7 on 2023-11-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_blogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='computer_game',
            field=models.BooleanField(default=False),
        ),
    ]
