# Generated by Django 4.2.7 on 2023-11-19 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_chesslobby_computer_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotInformation',
            fields=[
                ('bot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bot_account',
            field=models.BooleanField(default=False),
        ),
    ]
