# Generated by Django 4.2.7 on 2023-11-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_botinformation_user_bot_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='initiator_color',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
