# Generated by Django 4.2.7 on 2023-11-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_chesslobby_initiator_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesslobby',
            name='initiator_color',
        ),
    ]
