# Generated by Django 4.2.7 on 2023-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_chesslobby_initiator_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_reference',
            field=models.EmailField(default='temp@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
