# Generated by Django 5.0.1 on 2024-01-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_chesslobby_opponent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='solo_game',
            field=models.BooleanField(default=False),
        ),
    ]
