# Generated by Django 5.0.1 on 2024-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_chesslobby_solo_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activegames',
            name='status',
        ),
        migrations.AddField(
            model_name='chesslobby',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
        ),
    ]
