# Generated by Django 5.0.7 on 2024-08-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_activegames_status_chesslobby_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='gametype',
            field=models.CharField(default='', max_length=300),
        ),
    ]
