# Generated by Django 5.0.7 on 2024-08-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_chesslobby_gametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistorytable',
            name='state',
            field=models.TextField(default=''),
        ),
    ]
