# Generated by Django 5.1.1 on 2024-09-23 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_gamehistorytable_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedGames',
            fields=[
                ('embedded_game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FEN', models.CharField(default='', max_length=85)),
                ('gametype', models.CharField(default='', max_length=300)),
                ('indexed_moves', models.TextField(default='', null=True)),
                ('moves', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('url_name', models.CharField(default='', max_length=25)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_position', models.IntegerField(default=1)),
                ('content', models.TextField(default='')),
                ('tutorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons')),
            ],
        ),
    ]
