# Generated by Django 5.1.1 on 2024-09-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_embeddedgames_lessons_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedgames',
            name='name',
            field=models.CharField(default='exercise', max_length=50),
        ),
        migrations.AddField(
            model_name='pages',
            name='embedded_game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.embeddedgames'),
        ),
    ]
