# Generated by Django 5.1.1 on 2024-09-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_embeddedgames_name_pages_embedded_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedgames',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
