# Generated by Django 5.1.1 on 2024-09-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_embeddedgames_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='tutorial_id',
            new_name='lesson_id',
        ),
    ]
