# Generated by Django 5.1.1 on 2024-10-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_embeddedgames_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
