# Generated by Django 5.1.2 on 2024-10-24 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_message_inbox_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('white_id', models.UUIDField(null=True)),
                ('black_id', models.UUIDField(null=True)),
                ('initiator_name', models.CharField(default='Anonymous', max_length=150)),
                ('opponent_name', models.CharField(default='Waiting...', max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('initiator_color', models.CharField(max_length=5, null=True)),
                ('gametype', models.CharField(default='', max_length=300)),
                ('challenge_accepted', models.BooleanField(default=None)),
            ],
        ),
    ]
