# Generated by Django 5.1.2 on 2024-10-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='initiator_choice',
            field=models.CharField(choices=[('Random', 'Random'), ('White', 'White'), ('Black', 'Black')], default='Random', max_length=6),
        ),
    ]
