# Generated by Django 5.1.2 on 2024-10-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_challenge_initiator_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
