# Generated by Django 5.1.2 on 2024-10-26 19:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_challenge_challenge_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='game_id',
            field=models.UUIDField(null=True),
        ),
        migrations.CreateModel(
            name='ChallengeMessages',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_is_initiator', models.BooleanField(default=False)),
                ('sender', models.UUIDField()),
                ('sender_username', models.CharField(default='Anonymous', max_length=150)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.challenge')),
            ],
        ),
    ]
