# Generated by Django 5.1.2 on 2024-11-02 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='initial_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='initial_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='main.message'),
        ),
    ]
