# Generated by Django 5.1.2 on 2024-11-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_chesslobby_initial_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='subvariant',
            field=models.CharField(default='Normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chesslobby',
            name='subvariant',
            field=models.CharField(default='Normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='subvariant',
            field=models.CharField(default='Normal', max_length=20, null=True),
        ),
    ]
