# Generated by Django 5.1.2 on 2024-11-16 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_activegames_last_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='increment',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='increment',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
