# Generated by Django 5.1.2 on 2024-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_chesslobby_increment_gamehistorytable_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='black_rank_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chesslobby',
            name='match_type',
            field=models.CharField(default='Casual', max_length=6),
        ),
        migrations.AddField(
            model_name='chesslobby',
            name='white_rank_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='black_rank_new',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='black_rank_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='match_type',
            field=models.CharField(default='Casual', max_length=6),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='white_rank_new',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamehistorytable',
            name='white_rank_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_blitz',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_classical',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_complete_simple',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_complete_suggestive',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_countdown_simple',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_countdown_suggestive',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_normal',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_rapid',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_reveal_simple',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_reveal_suggestive',
            field=models.IntegerField(default=1500),
        ),
    ]
