# Generated by Django 5.1.2 on 2024-11-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_rename_black_rank_new_gamehistorytable_black_rank_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank_reveal_simple',
            new_name='rank_relay_simple',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rank_reveal_suggestive',
            new_name='rank_relay_suggestive',
        ),
    ]
