# Generated by Django 5.1.2 on 2024-11-17 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_rename_rank_reveal_simple_user_rank_relay_simple_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslobby',
            name='increment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gamehistorytable',
            name='increment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
