# Generated by Django 5.1.4 on 2024-12-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_image_activegames_fen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
