# Generated by Django 5.1.4 on 2025-01-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobby',
            name='FEN',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR', max_length=85),
        ),
        migrations.AlterField(
            model_name='activegames',
            name='FEN',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR', max_length=85),
        ),
    ]
