# Generated by Django 5.1.5 on 2025-02-01 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_reportedchats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('error_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.TextField()),
                ('script_type', models.CharField(default='decision_main', max_length=50)),
                ('error_message', models.TextField()),
            ],
        ),
    ]
